FROM amazonlinux:2

RUN amazon-linux-extras install docker -y \
    && yum clean all \
    && rm -rf /var/cache/yum
RUN yum install -y awscli
RUN yum install -y jq
RUN docker --version
RUN aws --version