FROM amazonlinux:2.0.20240131.0

# Clean up and free space before installing packages
RUN yum clean all && rm -rf /var/cache/yum \
	&& amazon-linux-extras install docker -y \
	&& yum install -y awscli jq \
	&& yum clean all && rm -rf /var/cache/yum \
	&& docker --version \
	&& aws --version